# This is an intial setup.py for building the extension
# against Flite 2.0.  It needs a bit of work as there
# are some undefined symbols when you load the python
# module.  The Makefile.linux may shed some light on the
# problem as that works.

from distutils.core import setup
from distutils.extension import Extension
from Cython.Build import cythonize

import os
FLITE=os.environ["FLITE"]
FLITE_INCLUDES = [FLITE+"/include", FLITE+"/lang/usenglish", FLITE+"/lang/cmulex"]
FLITE_LIBDIR = FLITE+"/build/x86_64-linux-gnu/lib"
FLITE_LIBDIR = FLITE+"/build/i386-cygwin/lib"

FLITE_2_LIBS = \
["flite",
"flite_cmu_grapheme_lang",
"flite_cmu_grapheme_lex",
"flite_cmu_indic_lang",
"flite_cmu_indic_lex",
"flite_cmulex",
"flite_cmu_time_awb",
"flite_cmu_us_awb",
"flite_cmu_us_kal16",
"flite_cmu_us_kal",
"flite_cmu_us_rms",
"flite_cmu_us_slt",
"flite_usenglish"]

FFLITE_2_LIBS = \
["libflite.a", 
"libflite_cmu_grapheme_lang.a", 
"libflite_cmu_grapheme_lex.a", 
"libflite_cmu_indic_lang.a", 
"libflite_cmu_indic_lex.a", 
"libflite_cmu_time_awb.a", 
"libflite_cmu_us_awb.a", 
"libflite_cmu_us_kal.a", 
"libflite_cmu_us_kal16.a", 
"libflite_cmu_us_rms.a", 
"libflite_cmu_us_slt.a", 
"libflite_cmulex.a", 
"libflite_usenglish.a",] 

FLITE_SOURCES=[ \
    FLITE+"/src/audio/audio.c",
    #FLITE+"/src/audio/auserver.c",
    FLITE+"/src/audio/au_command.c",
    FLITE+"/src/audio/au_none.c",
    FLITE+"/src/audio/au_streaming.c",
    #FLITE+"/src/audio/au_wince.c",
    FLITE+"/src/cg/cst_cg.c",
    FLITE+"/src/cg/cst_cg_dump_voice.c",
    FLITE+"/src/cg/cst_cg_load_voice.c",
    FLITE+"/src/cg/cst_cg_map.c",
    FLITE+"/src/cg/cst_mlpg.c",
    FLITE+"/src/cg/cst_mlsa.c",
    FLITE+"/src/cg/cst_spamf0.c",
    FLITE+"/src/cg/cst_vc.c",
    FLITE+"/src/hrg/cst_ffeature.c",
    FLITE+"/src/hrg/cst_item.c",
    FLITE+"/src/hrg/cst_relation.c",
    FLITE+"/src/hrg/cst_rel_io.c",
    FLITE+"/src/hrg/cst_utterance.c",
    FLITE+"/src/lexicon/cst_lexicon.c",
    FLITE+"/src/lexicon/cst_lts.c",
    FLITE+"/src/lexicon/cst_lts_rewrites.c",
    FLITE+"/src/regex/cst_regex.c",
    FLITE+"/src/regex/regexp.c",
    FLITE+"/src/regex/regsub.c",
    FLITE+"/src/speech/cst_lpcres.c",
    FLITE+"/src/speech/cst_track.c",
    FLITE+"/src/speech/cst_track_io.c",
    FLITE+"/src/speech/cst_wave.c",
    FLITE+"/src/speech/cst_wave_io.c",
    FLITE+"/src/speech/cst_wave_utils.c",
    FLITE+"/src/speech/g721.c",
    FLITE+"/src/speech/g723_24.c",
    FLITE+"/src/speech/g723_40.c",
    FLITE+"/src/speech/g72x.c",
    FLITE+"/src/speech/rateconv.c",
    FLITE+"/src/stats/cst_cart.c",
    FLITE+"/src/stats/cst_ss.c",
    FLITE+"/src/stats/cst_viterbi.c",
    FLITE+"/src/synth/cst_ffeatures.c",
    FLITE+"/src/synth/cst_phoneset.c",
    FLITE+"/src/synth/cst_ssml.c",
    FLITE+"/src/synth/cst_synth.c",
    FLITE+"/src/synth/cst_utt_utils.c",
    FLITE+"/src/synth/cst_voice.c",
    FLITE+"/src/synth/flite.c",
    FLITE+"/src/utils/cst_alloc.c",
    FLITE+"/src/utils/cst_args.c",
    FLITE+"/src/utils/cst_endian.c",
    FLITE+"/src/utils/cst_error.c",
    FLITE+"/src/utils/cst_features.c",
    FLITE+"/src/utils/cst_file_stdio.c",
    FLITE+"/src/utils/cst_mmap_win32.c",
    #FLITE+"/src/utils/cst_socket.c",
    FLITE+"/src/utils/cst_string.c",
    FLITE+"/src/utils/cst_tokenstream.c",
    FLITE+"/src/utils/cst_url.c",
    FLITE+"/src/utils/cst_val.c",
    FLITE+"/src/utils/cst_val_const.c",
    FLITE+"/src/utils/cst_val_user.c",
    FLITE+"/src/utils/cst_wchar.c",
    FLITE+"/src/wavesynth/cst_clunits.c",
    FLITE+"/src/wavesynth/cst_diphone.c",
    FLITE+"/src/wavesynth/cst_reflpc.c",
    FLITE+"/src/wavesynth/cst_sigpr.c",
    FLITE+"/src/wavesynth/cst_sts.c",
    FLITE+"/src/wavesynth/cst_units.c",
    FLITE+"/lang/cmulex/cmu_lex.c",
    FLITE+"/lang/cmulex/cmu_lex_data.c",
    #FLITE+"/lang/cmulex/cmu_lex_data_raw.c",
    FLITE+"/lang/cmulex/cmu_lex_entries.c",
    #FLITE+"/lang/cmulex/cmu_lex_entries_huff_table.c",
    #FLITE+"/lang/cmulex/cmu_lex_num_bytes.c",
    #FLITE+"/lang/cmulex/cmu_lex_phones_huff_table.c",
    FLITE+"/lang/cmulex/cmu_lts_model.c",
    FLITE+"/lang/cmulex/cmu_lts_rules.c",
    FLITE+"/lang/cmulex/cmu_postlex.c",
    FLITE+"/lang/cmu_grapheme_lang/cmu_grapheme_lang.c",
    FLITE+"/lang/cmu_grapheme_lang/cmu_grapheme_phoneset.c",
    FLITE+"/lang/cmu_grapheme_lang/cmu_grapheme_phrasing_cart.c",
    FLITE+"/lang/cmu_grapheme_lex/cmu_grapheme_lex.c",
    FLITE+"/lang/cmu_grapheme_lex/grapheme_unitran_tables.c",
    FLITE+"/lang/cmu_indic_lang/cmu_indic_lang.c",
    FLITE+"/lang/cmu_indic_lang/cmu_indic_phoneset.c",
    FLITE+"/lang/cmu_indic_lang/cmu_indic_phrasing_cart.c",
    FLITE+"/lang/cmu_indic_lex/cmu_indic_lex.c",
    FLITE+"/lang/cmu_time_awb/cmu_time_awb.c",
    FLITE+"/lang/cmu_time_awb/cmu_time_awb_cart.c",
    FLITE+"/lang/cmu_time_awb/cmu_time_awb_clunits.c",
    FLITE+"/lang/cmu_time_awb/cmu_time_awb_lex_entry.c",
    FLITE+"/lang/cmu_time_awb/cmu_time_awb_lpc.c",
    FLITE+"/lang/cmu_time_awb/cmu_time_awb_mcep.c",
    FLITE+"/lang/cmu_us_awb/cmu_us_awb.c",
    FLITE+"/lang/cmu_us_awb/cmu_us_awb_cg.c",
    FLITE+"/lang/cmu_us_awb/cmu_us_awb_cg_durmodel.c",
    FLITE+"/lang/cmu_us_awb/cmu_us_awb_cg_f0_trees.c",
    FLITE+"/lang/cmu_us_awb/cmu_us_awb_cg_phonestate.c",
    FLITE+"/lang/cmu_us_awb/cmu_us_awb_cg_single_mcep_trees.c",
    FLITE+"/lang/cmu_us_awb/cmu_us_awb_cg_single_params.c",
    FLITE+"/lang/cmu_us_awb/cmu_us_awb_spamf0_accent.c",
    FLITE+"/lang/cmu_us_awb/cmu_us_awb_spamf0_accent_params.c",
    FLITE+"/lang/cmu_us_awb/cmu_us_awb_spamf0_phrase.c",
    FLITE+"/lang/cmu_us_kal/cmu_us_kal.c",
    FLITE+"/lang/cmu_us_kal/cmu_us_kal_diphone.c",
    FLITE+"/lang/cmu_us_kal/cmu_us_kal_lpc.c",
    FLITE+"/lang/cmu_us_kal/cmu_us_kal_res.c",
    FLITE+"/lang/cmu_us_kal/cmu_us_kal_residx.c",
    FLITE+"/lang/cmu_us_kal/cmu_us_kal_ressize.c",
    FLITE+"/lang/cmu_us_kal16/cmu_us_kal16.c",
    FLITE+"/lang/cmu_us_kal16/cmu_us_kal16_diphone.c",
    FLITE+"/lang/cmu_us_kal16/cmu_us_kal16_lpc.c",
    FLITE+"/lang/cmu_us_kal16/cmu_us_kal16_res.c",
    FLITE+"/lang/cmu_us_kal16/cmu_us_kal16_residx.c",
    FLITE+"/lang/cmu_us_rms/cmu_us_rms.c",
    FLITE+"/lang/cmu_us_rms/cmu_us_rms_cg.c",
    FLITE+"/lang/cmu_us_rms/cmu_us_rms_cg_durmodel.c",
    FLITE+"/lang/cmu_us_rms/cmu_us_rms_cg_f0_trees.c",
    FLITE+"/lang/cmu_us_rms/cmu_us_rms_cg_phonestate.c",
    FLITE+"/lang/cmu_us_rms/cmu_us_rms_cg_single_mcep_trees.c",
    FLITE+"/lang/cmu_us_rms/cmu_us_rms_cg_single_params.c",
    FLITE+"/lang/cmu_us_rms/cmu_us_rms_spamf0_accent.c",
    FLITE+"/lang/cmu_us_rms/cmu_us_rms_spamf0_accent_params.c",
    FLITE+"/lang/cmu_us_rms/cmu_us_rms_spamf0_phrase.c",
    FLITE+"/lang/cmu_us_slt/cmu_us_slt.c",
    FLITE+"/lang/cmu_us_slt/cmu_us_slt_cg.c",
    FLITE+"/lang/cmu_us_slt/cmu_us_slt_cg_durmodel.c",
    FLITE+"/lang/cmu_us_slt/cmu_us_slt_cg_f0_trees.c",
    FLITE+"/lang/cmu_us_slt/cmu_us_slt_cg_phonestate.c",
    FLITE+"/lang/cmu_us_slt/cmu_us_slt_cg_single_mcep_trees.c",
    FLITE+"/lang/cmu_us_slt/cmu_us_slt_cg_single_params.c",
    FLITE+"/lang/cmu_us_slt/cmu_us_slt_spamf0_accent.c",
    FLITE+"/lang/cmu_us_slt/cmu_us_slt_spamf0_accent_params.c",
    FLITE+"/lang/cmu_us_slt/cmu_us_slt_spamf0_phrase.c",
    FLITE+"/lang/usenglish/usenglish.c",
    FLITE+"/lang/usenglish/us_aswd.c",
    FLITE+"/lang/usenglish/us_durz_cart.c",
    FLITE+"/lang/usenglish/us_dur_stats.c",
    FLITE+"/lang/usenglish/us_expand.c",
    FLITE+"/lang/usenglish/us_f0lr.c",
    FLITE+"/lang/usenglish/us_f0_model.c",
    FLITE+"/lang/usenglish/us_ffeatures.c",
    FLITE+"/lang/usenglish/us_gpos.c",
    FLITE+"/lang/usenglish/us_int_accent_cart.c",
    FLITE+"/lang/usenglish/us_int_tone_cart.c",
    FLITE+"/lang/usenglish/us_nums_cart.c",
    FLITE+"/lang/usenglish/us_phoneset.c",
    FLITE+"/lang/usenglish/us_phrasing_cart.c",
    FLITE+"/lang/usenglish/us_pos_cart.c",
    FLITE+"/lang/usenglish/us_text.c",  
    ] 

FLITE_LIBS = FLITE_2_LIBS


extensions = [
    Extension("flite", ["flite.pyx",]+FLITE_SOURCES,
        include_dirs = ["src",]+FLITE_INCLUDES,
        define_macros = [("CST_NO_SOCKETS","1")],
        #libraries = FLITE_LIBS,
        library_dirs = [FLITE_LIBDIR,],
        #extra_objects = [FLITE+"/build/i386-cygwin/obj/src/wavesynth/cst_diphone.o", ],
    ),
]
setup(
    name = "flite",
    ext_modules = cythonize(extensions),
)
